### ISSUE TITLE
[Feature] My new workflow system proposal

### ISSUE THREAD

**Issue by regularentropy** [Floorp-Projects/Floorp-PPA#1]
TLDR version:
### Old system:
New release → Manually packing the new version into the PPA repository → Update on Ubuntu

### Proposed system:
New release → Pull request with a new .deb package (can be automated in the future) → Merging → Signing and publishing a new release in PPA using GH Actions (not by hands, as it is right now)  →  Update on Ubuntu.

Workflow will remain the same as before, but the only needed thing will be a PR with a new .deb file. GitHub Action will do the rest.

**Comment by regularenthropy** [comment]
If something is hard to understand, please, contact me on Discord.

**Comment by creeper-0910** [comment]
Thanks for the issue!
This repository was set up for testing purposes and has now been replaced by ppa.ablaze.one.
However, maintenance will continue and we will try to implement the new system you suggested.
Thanks!

**Comment by regularentropy** [comment]
> Thanks for the issue! This repository was set up for testing purposes and has now been replaced by ppa.ablaze.one. However, maintenance will continue and we will try to implement the new system you suggested. Thanks!

Thank you for the reply. I already started implementing it, so I will open new PR when it's complete.

**Comment by creeper-0910** [comment]
Thank you!
The implementation for the new ppa.ablaze.one can be found at "https://github.com/Floorp-Projects/Floorp/blob/ESR102/.github/workflows/linux-build-x64-deb.yml".
 I hope you will take a look there too!

**Comment by regularentropy** [comment]
> Thank you! The implementation for the new ppa.ablaze.one is https://github.com/Floorp-Projects/Floorp/blob/ESR102/.github/workflows/linux-build-x64-deb.yml at I hope you will take a look there as well!

It's literally the same as mine, but mine was intended for usage specifically in this repo.
As it's being already implemented, I'm closing this proposal.

**Comment by creeper-0910** [comment]
Please let us know if you have any other concerns!
